GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Something about Rust",
    "author": "Amos",
    "url": "https://fasterthanli.me",
    "likes": 21
}